vtex-apps/render-runtime

- react/ExtensionPoint.js
- react/components/ExtensionPointComponent.js
- react/components/NestedExtensionPoints.js
- react/components/RenderProvider.js
- react/package.json
- react/utils/assets.js
- react/utils/events.js
- react/utils/messages.js
- react/yarn.lock
- Refactor ExtensionPoint and RenderProvider so they don't rely on context mutation to work
- Inject `pages-editor` components directly if they're available in the pre-determined extension points
- Extract component fetching logic into `ExtensionPointComponent`
> Fix ExtensionPoint and RenderProvider communication

- react/utils/client.js
As simple as activating `useGETForHashedQueries` in `persistedQueryLink`
> Enables GET for Persisted Queries

- react/components/ExtensionPointComponent.tsx
Adding this attribute avoid a form to be submitted if the component is rendered inside one.
> Add type attribute to button

- manifest.json
- react/ExtensionContainer.tsx
Pass down the props passed to an Extension Point that is an ExtensionContainer.
Example:
```js
render() {
return (
<div>
<ExtensionPoint id="order-actions" order={order} />
</div>
)
}
```
```json
"my-orders/order-actions": {
"component": "vtex.render-runtime/ExtensionContainer"
}
```
> Fix ExtensionContainer props

- manifest.json
- react/ExtensionContainer.tsx
We are trying to add an ExtensionContainer inside a list.
Example:
```html
<ul>
<li>App code</li>
<li>Extension 1</li>
<li>Extension 2</li>
</ul>
```
But this is not possible since ExtensionContainer renders a `<div>` to wrap the extensions.
```html
<ul>
<li>App code</li>
<div>
<li>Extension 1</li>
<li>Extension 2</li>
</div>
</ul>
```
This PR makes use of Fragment to avoid rendering this `<div>` element.
> Use Fragment instead of div

- manifest.json
- react/components/RenderProvider.tsx
Workspaces in production mode were not receiving new props when `render` was being called using render-extension-loader.
After a long debugging, we found out that extension points do not subscribe to `extension:{id}:update` in production mode. When `RenderProvider` is re-rendered an event is emitted specifically to the _root_ component, but it is not listening.
There are two options: 
1 - Make all extension points listen to `extension:{id}:update`
2 - Emit the event to all extension points (`extension:*:update`)
This PR takes the latter approach. One benefit is that it avoids creating more listeners that will only be used in _legacy-extensions_ scenarios. Also, if `RenderProvider` is receiving new props, we don't have any guarantees that only the _root_ extension have changed and we …
> Fix: re-render all extensions when changing RenderProvider props

- manifest.json
- react/components/ExtensionPointComponent.tsx
- react/typings/global.d.ts
- react/utils/logger.ts
Log client-side errors to Kibana.
- Link this `render-runtime` branch.
- Link an app containing an error within an Extension Point (such that, when rendering a page with this component, it will display the message `Error rendering extension point [path]`).
- Search for the log at Kibana within `metric-renderruntime-*` or `metric-renderruntime-jserror-*`. It should display the corresponding `account`, `workspace`, `message`, `path`, `stack` and `componentStack`.
> Log client-side errors to Kibana

- manifest.json
- react/utils/components.ts
Without that `common.js` is coming after other scripts when you have multiple imports like: 
```
import { IconSearch, IconShoppingBag, IconUser } from 'gocommerce.styleguide-store'
```
> Fix prepend uniq

- manifest.json
- react/components/NestedExtensionPoints.tsx
- react/components/RenderProvider.tsx
- react/core/main.tsx
- react/index.tsx
- react/start.ts
- react/typings/global.d.ts
- react/typings/node.d.ts
- react/utils/assets.ts
- react/utils/client/index.ts
- react/utils/dom.tsx
- react/utils/events.ts
- react/utils/locales.ts
- react/utils/pages.ts
We were using `global` as it was always `=== window`, but it can be overwritten by other developers.
> Always use window instead of global

- manifest.json
- react/components/RenderProvider.tsx
- react/typings/global.d.ts
- react/typings/node.d.ts
- react/utils/assets.ts
Merge "custom" locale messages from components (i.e. messages not included in the `react/locales` folder) before rendering.
The component that provides the "custom messages" should have a static method `getCustomMessages`, which receives a string representing the locale (e.g. `pt-BR`) and returns an object with key-value pairs corresponding to the id's and messages.
- Link this `render-runtime` branch.
- Link a component containing a static method `getCustomMessages` that returns some messages whose id's / messages are not contained in the files at `react/locales`.
- Use some of those "new" id's (with a `FormattedMessage` component, for example), and check if they are adequately rendered.
> Merge locale custom messages from components

- manifest.json
- react/utils/withHMR.tsx
Some developers need to share functions between apps, using our "dynamic code dependency" AKA calling functions from `__RENDER_7_COMPONENTS__` registry.
But if you export a function, we assume that it is a react functional component and we wrap it with our `HRMComponent` HOC.
The solution is to export an object with your function, but we are returning `null` to `__RENDER_7_COMPONENTS__` if you are not exporting a react class ou function. This PR removes this restriction.
> Register any entrypoint export

- CHANGELOG.md
- manifest.json
- react/utils/treePath.tsx
This enables sorting numeric treePaths or ending with numbers properly
Ex: ['b20', 'a0', 'a10', 'a1', '11', 'b2', '2', '1', '10'] becomes ['1', '2', '10', '11', 'a0', 'a1', 'a10', 'a11', 'b2']
Fixes #67
> Fix sorting direct children with numeric values

- manifest.json
- react/utils/client/generateHash.ts
Removes hash generation from directives to force error and send the correct query while this PR #62 is not merged
> Removes hash generation from directives

- manifest.json
- react/components/RenderProvider.tsx
- react/package.json
- react/typings/global.d.ts
- react/utils/client/generateHash.ts
- react/utils/client/index.ts
- react/utils/client/links/runtimeContextLink.ts
- react/utils/client/links/uriSwitchLink.ts
- react/utils/client/links/versionSplitterLink.ts
- react/utils/runtime.graphql
- react/utils/runtime.ts
Users `cacheHints` exported by `runtime` to correctly switch the endpoint for each query
> Automatic cache control split

- manifest.json
- react/utils/client/links/omitVariableTypenameLink.ts
Remove keys doesn't work because react/apollo use Object.freeze. 
The solution was to revive the object and manually copy streams with deepCopyFiles
> Deep clone copies streams

- CHANGELOG.md
- react/components/Link.tsx
Fix link props passed to DOM element
Link props were being passed to the `a` element, resulting in things like
```html
<a href="/login" to="/login" runtime="[object Object]">...</a>
```
> Fix link props passed to DOM element

- CHANGELOG.md
- manifest.json
- react/core/main.tsx
- react/index.tsx
- react/package.json
- react/typings/global.d.ts
- react/utils/client/index.ts
- react/yarn.lock
After the changes made in store-graphql, all types have a cacheId field. These fields will be used for caching using apollo inmemory cache, increasing the page performance and decreasing the number of requests after a mutation.
> Uses cacheId instead of id for caching

- CHANGELOG.md
- manifest.json
- react/components/Loading.tsx
- react/utils/assets.ts
The `store/__loading` implementation was being fetched using `window.__RUNTIME__.extensions`, but that is not available to legacy-extensions.
> Fix loading component

- manifest.json
- react/ExtensionPoint.tsx
- react/components/ExtensionPointComponent.tsx
- react/components/Link.tsx
And stop adding `EditableExtensionPoint` around extension points.
> Add data-extension-point hint to DOM element if component is editable

- CHANGELOG.md
- manifest.json
- react/components/NestedExtensionPoints.tsx
- react/components/RenderProvider.tsx
- react/typings/global.d.ts
- react/utils/pages.ts
Currently, the url is the source of truth for generating the route params. For example, if we are under a product's path template (`/:slug/p`), and under the url `/tesla-3/p`, the params generated for this route will be: `{slug: tesla-3}`.  
From now on, this will no longer be the truth, since canonical routes change the url. In order to generate correctly the parameters for a route, we retrieve it from the new field available in the runtime called `route`, containing all route metadata necessary to generate the params. Note that we only need it in canonical routes, and navigation will not be affected since navigation is done by using system routes
> Uses route info for generating params

- CHANGELOG.md
- manifest.json
- react/typings/global.d.ts
- react/utils/client/index.ts
- react/utils/client/links/uriSwitchLink.ts
Currently, when a `PersistedQueryNotFound` error is thrown, the system redos the query using the same HTTP verb with the whole stringified version of the query. If it turned out to be a public graphql query, the whole query text will be stringified into the request's querystring, putting too much pressure into the browser and our systems. 
This PR solves this issue by using GET in the first fetch, and POST in case of error
> Should use post on persisted query not found

- CHANGELOG.md
- manifest.json
- react/components/RenderContext.tsx
It fixes this issue with refs: "Warning: Stateless function components cannot be given refs. Attempts to access this ref will fail."
> Change withEmitter HOC to return a class

- CHANGELOG.md
- manifest.json
- react/utils/client/index.ts
- react/utils/client/links/persistedQueryVersionLink.ts
This PR replaces the Apollo persisted query version from 1 to the app that is sending that specific request. It does so with the help of an apollo link strategically placed after an Apollo's `PersistedQueryLink` and replacing it's content with the app available inside the query
> Adds app version to Persisted Query request

- CHANGELOG.md
- manifest.json
- react/components/RenderProvider.tsx
Now, the `vtex.store` is making a prefetch on context providers. But the Brastemp use case doesn't define the same pages that exist in `vtex.dreamstore`. This PR is to avoid the error below. 
**First commit is to adjust the to eslint**
> Avoid making prefetch of a page that doesn't exist.

- CHANGELOG.md
- manifest.json
- react/start.ts
We will soon exceed our quota in sentry.io. 
This PR makes the runtime to log component related errors only
> Log component error only to Sentry

- CHANGELOG.md
- manifest.json
- react/components/RenderProvider.tsx
Route class was deleted when navigating from/to routes with same category.
This PR fix this issue.
> Fix replace route class

- CHANGELOG.md
- manifest.json
- react/components/RenderProvider.tsx
- react/utils/pages.ts
There are two bug fixes here. This version is linked [here](https://fixscrolltopolyfill--boticario.myvtex.com/).
There's a bug report where, in an old chrome version, people would click links that should result in a `window.scrollTo({left: 0, top: 0})` call but don't. That happens because on those versions (60 or less) the `window.scrollTo` function with an object, like that, doesn't exist, the only available is `window.scrollTo(x,y)`. This pull request fixes that bug.
The bug was verified through [browserling](https://www.browserling.com/) and the fix was tested both there and by the person who reported the bug.
When the page should scroll, if `shouldFetchNavigationData` is true, the `afterPageChanged` function called was not passing the `scrollOptions` through.
This second fix also …
> Fix scroll related bugs

- CHANGELOG.md
- manifest.json
- react/components/RenderProvider.tsx
- react/typings/global.d.ts
Update iframe messages on locale change and HMR.
Outer runtime (running `admin`) had no way to know that the iframe runtime i18n messages changed.
Workspace: https://fixruntimecustommessages--lojadaju.myvtex.com/admin/cms/storefront.
- Bug fix (a non-breaking change which fixes an issue)
> Update iframe messages on locale change and HMR

- CHANGELOG.md
- manifest.json
- react/components/RenderProvider.tsx
- react/utils/messages.ts
Locale HMR is not working because:
- Locale comparison is done incorrectly. We are trying to check if `pt` equals `pt-BR`
- GraphQL cache is used by `render-runtime` after update, so it sees no changes.
This PR remove both issues and fixed locale HMR.
> Fix locale HMR

- CHANGELOG.md
- manifest.json
- react/components/MaybeAuth.tsx
Before, when the user not logged went to account page, it redirected to the login page and the returnUrl was setted to the login page instead of the account one. So I fixed it. [Check it out.](https://waza--storecomponents.myvtex.com/)
> Avoid MaybeAuth navigate to the login page when it is already navigating to it

- CHANGELOG.md
- manifest.json
- react/components/RenderProvider.tsx
- react/typings/global.d.ts
This PR fixes the component editor form UX.
The flag was necessary because otherwise we were needlessly updating the whole application and making the UX really terrible.
> Create flag to update runtime

- CHANGELOG.md
- manifest.json
- react/typings/global.d.ts
- react/utils/pages.ts
Allow scroll after navigate to target elements and not just absolute positions.
> Scroll element into view when elementId is passed to scroll options

- react/components/LayoutContainer.tsx
Completing @firstdoit work on above the fold.
If the `aboveTheFold : number` prop is set on any `LayoutContainer` it'll render only it's first `aboveTheFold` elements on the server side. Once the component is rendered on client side it'll render the other elements.
The last commit introduces the `preview : boolean` prop. If set to `true`, it won't render elements that are below the fold on the client side.
@brunoabreu and @tlgimenes, I'm not sure we'll need the preview prop. I've added it anyway and if we don't need it I'll just strip the commit.
> Above the fold and preview props on LayoutContainer

- public/externals.json
This PR uses a custom bluebird instance in SSR. This is necessary for not messing around with render's promises and ultimately throwing unecessary `unhandledPromiseRejection` errors in render-server
> Use custom bluebird for SSR

- CHANGELOG.md
- manifest.json
- react/package.json
- react/yarn.lock
`eventsource-polyfill` was being used by a dependency leak in builder-hub. After version 0.45.0, there are no more dependency leaks, and thus, the necessity of adding this library. Since it is only used in dev time for hot module replacement, this dependency is added as a `devDependency`
> Adding eventsource-polyfill as dev dependency

- CHANGELOG.md
- react/core/main.tsx
Adds `rel="noopener"` for any `target="_blank"` anchors.
Read more: https://developers.google.com/web/tools/lighthouse/audits/noopener
> Forbid external links to receive current window

- CHANGELOG.md
- manifest.json
- react/components/ExtensionPointComponent.tsx
This PR fixes displaying an error message before the fetched script has been executed - specifically, before the component has registered itself to the `__RENDER_7_COMPONENTS__` global variable. Apparently, this happens because we may re-enter `componentDidUpdate` several times before the component script has been fetched/executed.
Therefore, this PR displays an error message only when both:
- the promise for fetching the script has been resolved
- there was still no corresponding implementation for the component
> Do not throw error until fetchComponent promise has been resolved

- CHANGELOG.md
- manifest.json
- react/core/main.tsx
Add again the crossorigin attribute to img tags now that the store service worker cleans old opaque responses (this will solve the "images not loading" bug).
> Add again the crossorigin attribute to img tags

- CHANGELOG.md
- manifest.json
- react/utils/client/links/uriSwitchLink.ts
This PR is related to [this one](https://github.com/vtex/builder-hub/pull/284) and changes the graphql routes to match the new ones `builder-hub` exposes.
> Changing graphql routes to use new route system

- CHANGELOG.md
- manifest.json
- react/components/Link.tsx
AMP validator is complaining that the anchor tag has an invalid attribute `query`.
> Remove invalid property on anchor tag

- CHANGELOG.md
- manifest.json
- react/utils/assets.ts
Without this attribute, the service worker receives two kinds of responses:
1. On SSR, receives the 200 status (cors) response
2. On the client-side, receives the 0 status (opaque) response
This is making our master workspace go wild when refreshing a client-side cached route...
> Add the crossOrigin attribute to scripts added to the page

- CHANGELOG.md
- manifest.json
- react/core/main.tsx
The problem with the `crossOrigin` attribute was the "real crossorigin" hosts. Our `vteximg` hosts can handle crossorigin requests while some other hosts (clearsale, for example) can't. If we don't know which host can handle crossorigin, we trust only our hosts.
Crossorigin is necessary mostly because of caching. To cache images from other host (like vteximg), we need this. Otherwise, the responses are [opaque with huge size](https://cloudfour.com/thinks/when-7-kb-equals-7-mb/).
[Access the workspace to see it working](https://pwa--boticario.myvtex.com/)
> Add the crossOrigin attribute only to img tags with src from vteximg

- CHANGELOG.md
- manifest.json
- react/components/RenderProvider.tsx
- react/package.json
- react/queries/appMessages.graphql
- react/queries/messages.graphql
- react/queries/navigationPage.graphql
- react/queries/routePreviews.graphql
- react/typings/global.d.ts
- react/utils/messages.ts
- react/utils/routes.ts
This PR depends on the following  PRs: 
1. [messages](https://github.com/vtex/messages-graphql/pull/1), 
2. [builder-hub](https://github.com/vtex/builder-hub/pull/330)
3. [graphql-server](https://github.com/vtex/graphql-server/pull/137)
4. [pages-graphql](https://github.com/vtex/pages-graphql/pull/105)
Its purpose is to use the IOMessage type to translate automatically data.
This PR adapts render-server to the new pages-graphql that uses IOMessage for automatic translation.
> Automatic translation with IOMessage

- CHANGELOG.md
- public/externals.json
The script injection is now handled by the `vtex.request-capture-app`, and there's no need anymore for render to handle this.
> Remove RC external script

- CHANGELOG.md
- manifest.json
- react/utils/pages.ts
You (or anyone, really) can now pass a `replace` flag in the options for the `navigate` function that the runtime will use `history.replace` instead of `history.push` for navigation.  `push` will use as a default.
Used it [here](https://github.com/vtex-apps/store-components/pull/282)
> Allow using history's replace

- CHANGELOG.md
- manifest.json
- react/core/main.tsx
- react/utils/vteximg.ts
Fixes the following situation: Using helmet from render-runtime to add an inline style (example below) won't work because `props.style` is `read-only` in some moment.
```
<Helmet>
<style>{'p { background-color: #000; }'}</style>
</Helmet>
```
> Check if props.style is writable before assignment

- CHANGELOG.md
- manifest.json
- react/core/main.tsx
- react/utils/vteximg.ts
Fixes the following situation: Using helmet from render-runtime to add an inline style (example below) won't work because `props.style` is `read-only` in some moment.
```
<Helmet>
<style>{'p { background-color: #000; }'}</style>
</Helmet>
```
> Check if props.style is writable before assignment - 7.x

- .vtexignore
- CHANGELOG.md
- manifest.json
- react/.babelrc
- react/jest.config.js
- react/package.json
- react/tsconfig.json
- react/tsconfig.test.json
- react/utils/treePath.test.tsx
- react/utils/treePath.tsx
- react/yarn.lock
The dollar sign is used in some special blocks names (`$after`, `$before`, `$around`) and the Regexp for detecting a direct child wasn't working due to `$` being a regex modifier.
Also, configure `jest` on this project.
> Fix direct child not working with '$'

- CHANGELOG.md
- manifest.json
- react/components/ExtensionManager.tsx
- react/components/ExtensionPortal.tsx
- react/components/RenderProvider.tsx
- react/core/main.tsx
- react/typings/global.d.ts
- `renderExtension`: Given an `HTMLElement` and an `ExtensionName` the extension will be rendered using React Portals on the given `HTMLElement`. This feature will replace `RenderExtensionLoader`.
> Add renderExtension function to __RENDER_8_RUNTIME__

- CHANGELOG.md
- manifest.json
- react/components/RenderProvider.tsx
- react/typings/global.d.ts
Add a property that is present inside `__RUNTIME__` but not inside context.
This property is useful to get query string parameters.
> Add query to context (8.x)

- CHANGELOG.md
- manifest.json
- react/components/RenderProvider.tsx
- react/typings/global.d.ts
Add a property that is present inside `__RUNTIME__` but not inside context.
This property is useful to get query string parameters.
> Add query to context (7.x)

- CHANGELOG.md
- manifest.json
- react/utils/withHMR.tsx
Fixes bug where functions would be wrapped around components on HMR, and would be rendered unable to be called.
> Fix IO function export (for linked apps)

- CHANGELOG.md
- manifest.json
- react/components/ExtensionPoint.tsx
- react/typings/global.d.ts
Adds support for `layoutMode` (i.e. any component can be a `LayoutContainer` if it wants to)
Works in tandem with https://github.com/vtex/builder-hub/pull/443 and https://github.com/vtex/pages-graphql/pull/148
> Add layoutMode support

- CHANGELOG.md
- manifest.json
- react/components/RenderProvider.tsx
- react/typings/global.d.ts
This is useful for selecting variations on ProductPage and, when the user comes back, doesn't make him/her go all the way through the previously selected sku's.
Test it [here](https://ribeiraopreto--delivery.myvtex.com/). I've set `replace` to true.
> Adding replace option for setQuery

- CHANGELOG.md
- manifest.json
- react/components/ChildBlock.tsx
- react/components/ExtensionPoint.tsx
- react/core/main.tsx
- Exports ChildBlock and useChildBlock APIs without the `unstable` flag.
- Makes ChildBlock the props of the block, inserted via the `blocks.json` file.
- Sends props inserted via the `blocks.json` file to the `props` object of each child (when the composition is set to `children`)
- Exports `Block` component, which is an alias of the `ExtensionPoint` component.
- Deprecates `Unstable__ChildBlock` and `useChildBlock__unstable`, in favor of the proper names.
- Deprecates the name `ExtensionPoint` in favor of `Block`.
> Feature/child props and ChildBlock

- CHANGELOG.md
- README.md
- lint.sh
- manifest.json
- react/components/RenderProvider.tsx
- react/typings/global.d.ts
- react/yarn.lock
Related PR that should be released firstly: [store](https://github.com/vtex-apps/store/pull/211)
Test [here](https://cafedovento--storecomponents.myvtex.com/) using our search, changing the sort option, and going back. It didn't work before.
This is part of the mecanism to make possible the user navigate to `/shoes`, _shoes_ being a category, and get that page relative to a _category_. When someone accesses `/shoes/c` for the first time we save that registry and `/shoes` is now a category path, and we redirect now a user that tries to navigate to `/shoes/c`.
But that means that we would have to have two navigations for a simple transition, and with every navigation we fetch some heavy data on `pages-graphql`. To avoid fetching the same data again unnecessarily, there was the `if …
> Removing check for the back navigate and add scrollOptions option

- CHANGELOG.md
- manifest.json
- react/components/RenderProvider.tsx
- react/utils/pages.ts
as title says.
When passing params not specified in [routes template](https://github.com/vtex-apps/store/blob/master/store/routes.json), none of warn is displayed. 
1. [Acess this workspace](https://mariana--storecomponents.myvtex.com)
2. Create a navigate object passing more params then necessary e.g `navigate({page: 'store.product',
params: { slug: 'traveler-backpack', batata: 'batata', banana: 'banana', a:'a'},})`
3. And check if console throws this warn : 
`pages.ts:116 The following params are invalid:
batata
banana
a`
> Fix route receiving invalid params

- CHANGELOG.md
- manifest.json
- react/components/RenderProvider.tsx
- react/typings/global.d.ts
- Add setter to `sendInfoFromIframe` and fix typings;
- Fix `isStorefrontIframe` definition;
- Remove unused imports.
Lack of a way to update the Storefront iframe messages from the outer Runtime.
(Related: https://github.com/vtex-apps/admin-pages/pull/191)
Workspace: https://i18n--storecomponents.myvtex.com/admin/cms/storefront.
- New feature (a non-breaking change which adds functionality)
> Feature - Update messages

- CHANGELOG.md
- README.md
- manifest.json
- react/utils/pages.ts
as title says.
When passing query in `to` path, the query object is empty, and search field needs of this values
1. [Acess this workspace](https://fanny--storecomponents.myvtex.com)
2. Create a navigate object passing more params then necessary e.g `navigate({to: '/classic-shoes/p?map=ft'})`
3. And check if `query` object contains `map` field.
> Fix to param of navigate object

- CHANGELOG.md
- manifest.json
- react/components/RenderProvider.tsx
- react/queries/navigationPage.graphql
- react/typings/global.d.ts
- react/utils/pages.ts
- react/utils/routes.ts
This PR has two features.
It was created originally to fix route matching with `?map` query string. For instance, `/smartphones/White?map=c,specification_filter10` should be identified as a _department_ page, but is being identified as a _category_ page because we only use path segments to decide which route matches. The first commit handles it.
Then this fix brought us another issue with canonical paths. The department path is `/:department/d` and has a canonical `/:department`, but if I browse `/smartphones/White?map=c,specification_filter10` I should not be redirected to `/smartphones?map=c,specification_filter10`, and `vtex.store` was doing that.
Now render-runtime will handle canonical path replacements with the benefit of doing a single history push, instead of going to …
> Fix routing issues

- CHANGELOG.md
- manifest.json
- react/components/RenderProvider.tsx
The `paramsJSON` sent when calling `updateRuntime` is always empty. It makes pages-graphql response wrong, because it can not identify the page properly.
> Fix updateRuntime params

- CHANGELOG.md
- manifest.json
- react/components/RenderProvider.tsx
- react/typings/global.d.ts
- Method to add messages to Runtime (`addMessages`).
- `addMessages` and `messages` to Render context.
- `sendInfoFromIframe` signature.
- `updateExtension` and `updateRuntime` now await for `setState` to be finished.
- `RenderProvider`'s `updateMessages` private method.
- `sendInfoFromIframe`'s 4th argument (`setMessages`).
> Feature - Add messages

- CHANGELOG.md
- manifest.json
- public/config.json
- react/components/ExtensionPointComponent.tsx
- react/components/ExtensionPointError.tsx
- react/package.json
- react/start.ts
- react/typings/global.d.ts
- react/typings/node.d.ts
- react/utils/client/index.ts
- react/utils/graphQLErrorsStore.ts
- react/yarn.lock
In this PR:
[Workspace](https://operationiderror--storecomponents.myvtex.com/)
I wasn't able to send an event in the workspace :(. Any idea why? What I did was commenting the `if` around the Sentry functions and using the `prod` environment instead of `staging`...
> Print operation id on error

- react/error.tsx
- react/start.ts
Allows start.js and error.js to be used in the same page. This makes render-server code easier, by just adding these extra scripts on error pages
> Support error on streaming

- CHANGELOG.md
- react/utils/client/links/uriSwitchLink.ts
This PR makes the following changes:
- Sets every URI scope to `private` whenever the workspace's root interface app has a `requiresAuthorization` setting with value `true`.
> Feature b2b

- CHANGELOG.md
- react/core/main.tsx
For example, https://shop.samsung.com/ar/ has a hanging script which makes images not load for a long time. 
Still enables lazysizes as opt-in
> Revert automatic src to data-src

- CHANGELOG.md
- react/package.json
- react/yarn.lock
GoCommerce was suffering with queries being stucked in loading state. It doesn't seem to happen in the latest version of Apollo.
> Upgrade apollo-client and react-apollo

- react/externals.json
- react/package.json
- react/utils/client/links/versionSplitterLink.ts
- react/yarn.lock
This temporarily maintains `externals.json` in two folders (`public/` and `react/`) to make it compatible with Builder-hub's buildExports feature. Once https://github.com/vtex/builder-hub/pull/564 is merged, the old location can be safely deleted.
> Copy externals.json to react folder

- CHANGELOG.md
- react/components/ExtensionPoint.tsx
- react/utils/client/links/versionSplitterLink.ts
Before | After
---|---
https://breno--alssports.myvtex.com/billab-crossfire-x-short/p?skuId=400192
> Avoid recreating React elements when block has composition children

- CHANGELOG.md
- react/utils/pages.ts
Fix issue if one tried to use:
```jsx
<Link to="#foo" />
```
It would redirect to the wrong page. 
Example:
https://hashbug--storecomponents.myvtex.com/shirt/p
Click in "2 Reviews"
It goes to https://hashbug--storecomponents.myvtex.com/shirt/#reviews (?)
Now it just use the `location.hash` instead of trying to find which page it's trying to go, a history navigation, etc.
Linked workspace:
https://breno--storecomponents.myvtex.com/shirt/p
Click in "2 Reviews"
It goes to https://breno--storecomponents.myvtex.com/shirt/p#reviews
> Fix hash navigation in Link component

- CHANGELOG.md
- react/typings/global.d.ts
- react/utils/blocks.ts
Pass hasContentSchema information from blocks to extensions
Should be merged after this PR: https://github.com/vtex/pages-graphql/pull/241
Workspace to test: https://jey2--storecomponents.myvtex.com
How to test:
1 - Open https://jey2--storecomponents.myvtex.com
2 - Open the dev console 
3 - See that inside each `__RUNTIME__.extensions` we have an attribute called `hasContentSchema`
> Feature extensions content schema

- CHANGELOG.md
- react/utils/pages.ts
Fixes the optional parameters support in routes containing `map`
> Removes trailing parenthesis

- CHANGELOG.md
- react/utils/blocks.ts
Pass `block.title` to `generateExtension` function result.
[ch14958]
> Get block title when mounting extensions

- CHANGELOG.md
- react/components/Link.tsx
In admin builder, all internal links must be `/admin/app/*anything` to proper appear inside of the iframe.
But due to this, if user access the link directly, like when you open in a new tap, he will open the `/admin/app/` url, and will se the admin without the sidebar.
With this change, the href show properly, so now user can open in a new tap without worry:
**How this works**
The `href` attribute is just a fallback for the browser, when the user click in a link, he will call the function on `onClick`, and this one will still use the correct `/admin/app/` pattern.
> Change href for links inside admin iframe

- CHANGELOG.md
- react/components/ChildBlock.tsx
- react/components/ExtensionPoint.tsx
- react/components/Loading.tsx
- react/core/main.tsx
- react/hooks/extension.tsx
- react/utils/extension.tsx
`ExtensionPoint` render is interrupted earlier if no extension is found, and refrains from rendering `ExtensionPointComponent` if so.
Also fixes an issue on the Loading component which wouldn't render properly if inserted by an app.
https://lbebber--alssports.myvtex.com/
> Refrain from rendering empty extensions

- CHANGELOG.md
- react/components/RenderProvider.tsx
- react/utils/client/links/uriSwitchLink.ts
- react/utils/dom.tsx
It will change admin's language without changing store's language.
It should only be merged after this one: https://github.com/vtex/node-vtex-api/pull/190
Test: https://jey--storecomponents.myvtex.com/admin/cms/storefront
1 - Select an admin language.
2 - At storefront's topbar, select a different language for the store.
3 - Store language now should be different from admin's language.
> Feature separate admin lang from store lang

- CHANGELOG.md
- react/typings/global.d.ts
- react/utils/client/index.ts
Use IntrospectionFragmentMatcher in `ApolloClient`'s cache so `Unions` and `Interfaces` can be used in graphql 🎉
> Use IntrospectionFragmentMatcher instead of HeuristFragmentMatcher

- CHANGELOG.md
- react/components/NoSSR.tsx
In some cases, the `useEffect` was taking too long to finish.
One example is in GoCommerce admin navigation, the delay was of around 10s to show the page after load finish.
With this change, the delay was decreased to 1s.
Code inspiration from: https://github.com/mui-org/material-ui/blob/master/packages/material-ui/src/NoSsr/NoSsr.js#L5
> Enhanced `NoSSR` detection

- CHANGELOG.md
- react/components/RenderProvider.tsx
We have a very common scenario in GC where the admin crashes after a runtime update. One example is when removing an app. After the success we trigger  an `updateRuntime` effect, but we also need to redirect the user back to the app store. The admin crashes because the update removed the desired route from the extensions object.
To revoke an app: https://github.com/vtex/admin-apps/blob/master/react/withAppSetup.js#L121
It breaks here: https://github.com/vtex-apps/render-runtime/blob/master/react/components/MaybeContext.tsx#L19
> Prevent overwriting older extensions

- CHANGELOG.md
- react/components/RenderProvider.tsx
- react/core/main.tsx
- react/package.json
- react/tsconfig.json
- react/typings/global.d.ts
- react/yarn.lock
This PR reverts #370 because the `react-amphtml` dependency added there was injecting ES5 code in the browser, hence causing problems rendering in browsers like IE11.
> Revert #370

- CHANGELOG.md
- react/utils/assets.ts
Some web servers (and maybe browsers) use semicolon as query separator (just like &) and it is causing errors on asset-server bundle endpoint
https://stackoverflow.com/questions/3481664/semicolon-as-url-query-separator
> Deprecate semicolon as bundle files separator

- CHANGELOG.md
- react/components/RenderProvider.tsx
- react/typings/global.d.ts
- Add a pool to prefetch pages to only execute it once.
- Execute prefetch pages when there is no cpu usage `requestIdleCallback ` or after waiting for 3 secs
- Add querystring to disable prefetchPages: `__disablePrefetchPages`
> Delayed prefetch pages

- .prettierignore
- CHANGELOG.md
- react/utils/treePath.tsx
use React.memo with a component that uses the children prop can be quite problematic, using useMemo and tracking the treePath prop, is the better way
> use useMemo on tree path provider

- CHANGELOG.md
- react/components/ExtensionPoint.tsx
Prevents the so-called accordion effect on root ExtensionPoints.
Before (click around on the categories): https://lbebber--admitone.myvtex.com
After (do the same): https://accordion--admitone.myvtex.com/
> Fix/accordion: the return (quick win)

- react/components/RenderProvider.tsx
- react/utils/client/index.ts
- react/utils/fetch.ts
- react/utils/flags.ts
- react/utils/routes.ts
This PR adds window.fetch to render-runtime so we get immune to buggy monkey patch in window.fetch.
We are currently using the raw fetch for apollo queries and navigation
Also, this PR re-enables render navigation
> Use browser fetch always

- CHANGELOG.md
- manifest.json
- react/utils/fetch.ts
- react/utils/routes.ts
There is a weird bug when adding fetch to its init. This pr fixes this problem by removing fetch from fetch's init
> Fix runtime navigation

- CHANGELOG.md
- react/components/RenderProvider.tsx
It crashes navigation when going back using history because our algorithm expects `navigationRoute.path` to not include querystrings.
> Fix RenderHistoryLocation

- CHANGELOG.md
- react/utils/pages.ts
For SEO purposes, it was asked for us to stop encoding URL
on search, today we get: `/categoryA/categoryB?map=c%20c`, we will now have `/categoryA/categoryB?map=c,c`
We should watch this carefully
https://fidelis--invictastores.myvtex.com
https://encodequery--alssports.myvtex.com/
https://encodequery--samsungar.myvtex.com
https://encodequery--exitocol.myvtex.com
> stop encoding

- CHANGELOG.md
- react/index.tsx
- react/typings/global.d.ts
Register `react-amphtml` global mocks that throw an explicitly error when trying to use AMP components on client-side or out of a `runtime.amp` check.
> Fix external react-amphtml usage

- CHANGELOG.md
- react/components/ExtensionPoint.tsx
- react/core/main.tsx
- react/typings/global.d.ts
this PR updates the AMP page rendering to also disable server-side queries with the `disableSSQ` flag. I also moved some eslint configurations to the root folder, as it wasn't working correctly (at least in my editor).
I added some logic for the component lazy-load in the `ExtensionPoint` component, because we can't lazy load components in AMP pages, but if anyone feels a bit itchy about it I can remove that (right now I don't think it's working 100%, I still need to remove the `"render": "client"` on the Shelf app for it to render, if someone has any idea about it I'd highly appreciate hearing it).
> Use disableSSQ for AMP pages

- manifest.json
- react/utils/routes.ts
Links containing `#` breaks navigation, since we add the querystring after the path. This PR addresses this issue by using functions `format` and `parse` to correctly build the url
> Fixes navigation when there is a hashtag

- react/utils/pages.ts
The function `pathFromPageName` was returning only the canonical path, losing the filters. This created a bug that when the `setQuery` function was called the querystring and the path changes.
> Keeps filters in path

- react/utils/routes.ts
Allows to receive a `routeId` of the type `redirect`, that causes a redirect to the `path` of the JSON object.
> Treats redirect JSON

- CHANGELOG.md
- react/components/Link.tsx
Added support for special links using `mailto:` and `tel:` to the `<Link />` component.
Currently, this kind of link would result in a broken URL, as `runtime.rootPath` would get appended to the `href` attribute in the anchor tag rendered by `<Link />`.
Use the link in the header "Call Us" and "Mail Us"
https://speciallinksruntime--storecomponents.myvtex.com/
> Add support for special links to Link component

- CHANGELOG.md
- react/utils/routes.ts
When there isn't a querystring, the routePath shouldn't have `?` in it.
It was causing some issues in `admin-pages`, because by having `?`, the `updateRuntime` function makes a request without `__pickRuntime` (returning a HTML instead of a JSON).
This PR aims to fix this by relying on the behaviour that `stringify({}) === ''`.
> Remove unnecessary "?" from path

- react/components/RenderProvider.tsx
- react/typings/global.d.ts
- react/utils/routes.ts
Receives queryData from render-server and hydrates apollo cache with it.
Render a product page, watch the product query made in browser. There should be none that gets all the product info.
This depends on https://github.com/vtex/render-server/pull/504
> Receives queryData from render-server

- CHANGELOG.md
- manifest.json
- react/components/RenderProvider.tsx
- react/externals.json
- react/utils/client/index.ts
- react/utils/client/links/ensureSessionLink.ts
- react/utils/client/links/uriSwitchLink.ts
- react/utils/client/links/versionSplitterLink.ts
Revert the revert adding back the session ensurance for /segment and /private routes by fixing query split race condition with shared pointer
> Do not share extensions between requests

- CHANGELOG.md
- react/components/Preview/Text.tsx
- react/components/Preview/index.tsx
The `Box` preview type (image 1) was being showed before the `Text` one (image 2), even when it was not necessary. 
**Image 1**
**Image 2**
This PR fix it.
> Fix 'Box' preview being showed before the 'Text' preview appear

- CHANGELOG.md
- manifest.json
- react/components/Preview/Text.tsx
- react/core/main.tsx
- react/typings/exenv.d.ts
- react/typings/node.d.ts
- react/typings/render.d.ts
- react/utils/fetch.ts
- react/utils/reactApollo.tsx
- react/utils/registerComponent.tsx
Because of our CDN query string whitelist, only some query strings are available in `runtime.query`, not reflecting the truth on client-side.
> Add client-side query to __RUNTIME__

- CHANGELOG.md
- react/components/Preview/ContentLoader.css
- react/components/Preview/ContentLoader.tsx
We decided that the preview skeleton's animation velocity and its color contrast should be smaller. This PR does it.
**How to test it?**
- Go to [Workspace](https://fixskeleton--checkoutio.myvtex.com/cart)
- Open console dev tools
- Change network conditions to "Slow 3g", for instance.
- Reload
cc @lbebber @augustocb
> Change preview skeleton's gradient color contrast and velocity

- react/components/BuildStatus.tsx
- react/utils/events.ts
This PR, together with vtex/sse-server#6, makes the user see a "Link Interrupted" pop-up in the browser whenever a link process is interrupted in the current account/workspace.
> Notify on interrupted link

- CHANGELOG.md
- react/components/Link.tsx
- react/utils/pages.ts
When using the `<Link />` component, one usually makes a link to a specific page by simply stating:
```jsx
<Link
page={linkprops.page}
query={linkprops.querystring}
params={linkprops.params}
className="c-on-base f5 ml-auto db no-underline pv4 ph5 hover-bg-muted-4"
>
{option.label}
</Link>
```
As stated in this project's README.
However, when importing `Link` together with its types, one discovers that `onClick` and `modifiers` are required Link props, when in reality they never were. This proposed change, therefore, intends to fix the `Link`'s props types.
To test, visit [this link](https://test--sandboxintegracao.myvtex.com/admin/sellers) and click on the `Add Seller` link on the top right corner. It should cause a navigation to a new page as usual
> Update props for Link component

- CHANGELOG.md
- react/__tests__/RenderProvider.test.tsx
- react/components/RenderProvider.tsx
- react/package.json
- react/yarn.lock
- GC admin has been having some problems after the release of the 8.86.x version.
Why?
Because they have multiple components that call the navigate function on the component did mount or component did update logic. This is causing their admin to break at random moments, because by calling multiple navigates, some components are being rendered twice and falling on the fetchAndRerender throw sometimes.
- This PR adds a lock on render provider and if you try to navigate why an early navigate is not done, we early exit. I think this is a nice thing to have.
https://fidnav--alssports.myvtex.com/
https://fidnav--boticario.myvtex.com/
https://fidnav--tbb.myvtex.com/
https://fidnav--samsungar.myvtex.com/
https://fidnav--paguemenos.myvtex.com/
https://fidnav--exitocol.myvtex.com/ …
> protect render provider against multiple continuous navigates

- react/components/ExtensionPoint.tsx
- react/typings/global.d.ts
Adapt `render-runtime` to the changes made in `pages@1.x` builder by https://github.com/vtex/builder-hub/pull/856 . This means handling the fact that newly built interfaces are always `composition: 'blocks'` but we still support `children` being passed to blocks since we support both at the same time.
Tested in the following accounts:
- [Store Components](https://killallowed--storecomponents.myvtex.com/)
- [Footnotes](https://killallowed--footnotes.myvtex.com/)
- [Eriks Bikes](https://killallowed--eriksbikeshop.myvtex.com/)
- [Texas Boots](https://killallowed--txboot.myvtex.com/)
- [Motorola ES](https://killallowed--motorolaes.myvtex.com/) (They have a bug with their logo not showing up, not caused by this version of `render-runtime`)
- [Bisco …
> Unify compositions

- CHANGELOG.md
- react/components/ExtensionPoint.tsx
Fix rendering of children when it is `undefined`. This could cause an issue with components that use `React.cloneElement()`, as `undefined` could be passed to it.
The `vtex.tab-layout` was not being rendered properly after a build.
- [tack of the day](https://tack--tackoftheday.myvtex.com/)
- [Store Components](https://minicartchildren--storecomponents.myvtex.com/)
- [Boticário](https://runtimetest--boticario.myvtex.com/)
- [TBB](https://runtimetest--tbb.myvtex.com/)
> Fix broken rendering with undefined children

- CHANGELOG.md
- docs/README.md
- react/components/Link.tsx
The `Link` component could receive that prop already because his props extend the `NavigationOptions`, but it wasn't doing anything with it.
> Add replace prop to the Link component

- CHANGELOG.md
- react/components/RenderProvider.tsx
- react/typings/global.d.ts
Related to [this PR on pages-graphql](https://github.com/vtex/pages-graphql/pull/336).
**Big Picture**: Tech Solutions Internship project by Júlia Rocha to automatically generate documentation for Store Framework components
- **exposes the `fetchComponents`:** For her project to fetch some component implementation, we have to expose the `fetchComponents` functions to the `RenderProvider`, so she can import it from `useRuntime()`.
- **`extensions` argument to be optional:** The `fetchComponents` function has on its interface two arguments: _components_ and _extensions_. We only care about fetching a specific set of components, and those are not coupled with _extensions_, so, if only components are provided, I "mock" an `extensions` object that will match all provided components. I've …
> Allowing the `extensions` argument to be optional on `fetchComponents`

- CHANGELOG.md
- react/components/RenderPage.tsx
Reverts https://github.com/vtex-apps/render-runtime/pull/470, which was deprecated due to a bug on the admin.
A PR with the proper fix is incoming
> Revert "Merge pull request #470 from vtex-apps/fix/page-remount"

- CHANGELOG.md
- react/components/Link.tsx
The  `Link` component wasn't working properly when you try to use it with `target="_blank"`.
To test this you have to follow the steps:
1. Go to the [workspace](https://klynger--storecomponents.myvtex.com/)
2. Click on the `Quickview` text inside the `ProductSummary` to open the modal
3. Click on the `Mais Detalhes >` in the modal
To see the bug [access this workspace](https://linkbug--storecomponents.myvtex.com/) that doesn't have the changes and do the same steps
> Fix prop target of link not working properly

- react/externals.json
- react/package.json
Update `prop-types` package so `material-ui@4.x` works, otherwise it crashes with an error:
It crashes because it uses a new validator, `elementType`, added in [`15.7.0`](https://github.com/facebook/prop-types/blob/master/CHANGELOG.md#1570).
> Update prop-types version

- CHANGELOG.md
- docs/README.md
- react/components/RenderProvider.tsx
- react/components/useRuntime.ts
- react/typings/global.d.ts
- react/utils/pages.ts
To be used mostly on our _CRUDly_ admin apps, so they don't need to [hack](https://github.com/vtex/admin-collections/blob/f4f9270e848154bba4cf52e9968f9c2a13cf9e91/react/components/CollectionView/index.tsx#L107) when needing to only change the URL.
**How to test**
1. Go https://templo--storecomponents.myvtex.com/
2. Inspect a component `usingRuntime()` with React Dev Tools
3. `$r.props.runtime.navigate({ page: 'store.product', params: { slug: 'my-product' }, preventRemount: true })`
**P.S:** I've also removed the **Table of Contents** from README.md, since it gets messed up in VTEX IO Docs.
> Adding preventRemount prop

- CHANGELOG.md
- manifest.json
- react/components/RenderProvider.tsx
We don't need graphql-tag to hydrate apollo cache. This can be done with `parse` from graphql-js. Thus, this should remove a dep from render-runtime
> Remove graphql tag

- CHANGELOG.md
- react/utils/client/links/uriSwitchLink.ts
Fixes PersistedQueryNotFoundError. This fix includes:
- Adds query to request when persisted query is not found to avoid PersistedQueryNotFoundError from graphql-server
- Uses POST on those requests
- Throws error in development when persisted query is not found
> Fix persisted query not found

- CHANGELOG.md
- react/utils/dom.tsx
**What does this PR do?**
We need to make an app available for any costumer (VTEX and/or Indeva) to consume it through an iframe.
The variable `isSiteEditorIframe` is raising error when any vtex-app is consumed by an iframe using the render-runtime with react apps.
Examples:
- fixed iframe: https://ivan--indevasetup.myvtex.com/rihappy
- raising error: https://developers.vtex.com/docs/teste
```
Uncaught Error: An error happened while requiring the app vtex.render-runtime@8.100.1/index, please check your app's code.\nError: Blocked a frame with origin "https://vtex.io" from accessing a cross-origin frame.
https://vtexpages.vtexassets.com/_v/public/assets/v1/published/vtex.render-runtime@8.100.1/public/react/common.min.js?workspace=master
```
> fix: isSiteEditorIframe verification raising error on iframe consumer

- CHANGELOG.md
- react/utils/routes.ts
The url module used by the routes.ts is a node module. This means that only by just importing it, our builder-hub's webpack adds 1580+- lines of code (or 5kb gzipped) of unneeded code to our stores javascript payload. We can easily replace it with the native window.URL constructor.
Note: IE 11 doesn't have the `URL` and `URLSearchParams` constructors, but we're already polyfilling it [here](https://github.com/vtex/render-server/blob/master/node/utils/assetLoader.ts#L56).
Story: https://app.clubhouse.io/vtex/story/38530/remove-url-module-from-render-runtime
1) Go to https://kiwi--storecomponents.myvtex.com
2) Navigate to your heart's desire
Also tested the IE 11 polyfill via browserstack.
n/a
n/a
> Replace node URL module with window.URL

- CHANGELOG.md
- react/index.tsx
Stop using `Intl` from polyfill on SSR. Now we have node with full ICU data 🎉 
The polyfill does not cover some cases.
If you go here: https://npm.runkit.com/intl
and try: 
```js
var intl = require("intl")
console.log(new intl.NumberFormat('ro-RO', {style: 'currency', currency: 'RON', currencyDisplay: 'name'}).format(100))
```
You will get "100,00 RON", but it should be "100,00 lei românești".
It is linked and working here: https://breno--melimeloparis.myvtex.com/?__bindingAddress=www.melimeloparis.ro/&utm_source=fobar
> Stop overriding native Intl now we have full-icu on nodejs

- CHANGELOG.md
- react/utils/pages.ts
- Do not prepend root path if the destination path already has the root path.
We test if the destination path starts with `${rootPath}/`. So the result is:
For rootpath == `/br`
/brasil/fogao => will append and result in => /br/brasil/fogao
/shoes => will append and result in => /br/shoes
/br/shoes => will not append and will remain => /br/shoes
https://shop.samsung.com/br/eletrodomesticos/Geladeiras?map=c,c&workspace=teste
Click on a filter
> fix rootpath unneeded prepend

- CHANGELOG.md
- react/components/RenderProvider.tsx
- react/utils/pages.ts
- Prevents setQuery method to change the path when calling navigate.
The problem:
without this, when we try to call setQuery in a store with bindings, like powerplanet, the path will change. Example:
You are in binding pt-BR and the catalog language is es-ES.
you are seeing url: '/sapato-pt', that is the url for the pt-BR binding.
After doing a setQUery to change a query param, you will be navigated to: `/sapato-es`. Because the current architecture still keeps the params in the tenant language
I propose that a `setQuuery` should never attempt to change the path.
https://teste--powerplanet.myvtex.com/smartwatch/smartband?__bindingAddress=www.powerplanetonline.com/pt
go here and click on the xiaomi filter, see it work as expected
https://setquery--motorolaus.myvtex.com/ …
> prevent change path when set query is called

- CHANGELOG.md
- react/typings/global.d.ts
- react/utils/client/links/uriSwitchLink.ts
Check channelPrivacy to decide on query scope.
Open https://brunoh--motorolaus.myvtex.com/admin
Click on "use beta" at the end of the left menu.
Go to https://brunoh--motorolaus.myvtex.com
When browsing anonymously you will see product query requests with `/_v/segment/graphql`.
If you log in as a B2B consumer, those requests will be under `/_v/private/graphql`.
This feature will only work with `vtex.store-session@1.0.1-beta.0`, session service beta (vtexcommercebeta) and https://github.com/vtex/render-server/pull/642
In order to access session service beta, you will need a rewriter version that forwards the `vtex-commerce-env` cookie: https://github.com/vtex/rewriter/pull/159
In order to test it in a workspace, you will need the latest version of `@vtex/api` which can be yarn linked with …
> Check channelPrivacy to decide on query scope.

- CHANGELOG.md
- react/externals.json
Updates render-session to 1.9.1 ([this PR](https://github.com/vtex-apps/render-session/pull/28)).
> Update render-session to 1.9.1

- CHANGELOG.md
- react/components/ExtensionPoint/index.tsx
Adds a simple memoization to the `children` object passed down to blocks in order to enable memoization solely on the props, which can benefit components that render a lot of stuff to partially memoize some of the tree.
Use the same testing plan as vtex-apps/checkout-cart#61. The product list component has been memoized (and it wouldn't work without this PR because the children would change every render, making the memoization useless) in order to avoid rendering all of the products in the orderForm when you alter the quantity of only one of them.
One alternative would require a change in the product-list component itself, where it wouldn't depend on the children but would tigh the implementation of the product list item to the component itself and make any customizations the agencies …
> Add memo to blocks children

- CHANGELOG.md
- react/components/ExtensionPoint/index.tsx
- react/components/LayoutContainer.tsx
- react/components/LazyRender.tsx
Improves fold implementation and functionality, and adds support for lazy footer rendering, enabled via `enableLazyFooter` setting.
This PR also refactors the `LayoutContainer` class into a Function Component, and also simplifies its implementation a bit.
Before, if the user scrolled reasonably quickly, they would stumble upon the footer, which would promptly blink away, and then the whole rest of the page would render
With this PR, each concealed row adds its own empty spacer div, which brings the scroll area closer to the actual value. It also adds spacing between the above-the-fold content and the footer, which prevents the user from seeing it in most cases.
Also, since it renders the rows one by one, instead of the whole page in a single blow, the rendering should be much smoother, …
> Better fold + lazy footer

- CHANGELOG.md
- react/components/ExtensionPoint/SiteEditorWrapper.tsx
Uses an extension point's `hasContentChema` to check if the block used has a content schema.
It was tested in #526 😳 
(incoming test workspace)
https://github.com/vtex/pages-graphql/pull/375
> Check for hasContentSchema

- CHANGELOG.md
- react/components/LazyImages.tsx
Currently, if a lazyloaded `img` tag has its `src` attribute changed, our monkey patched `img`s are not changing the `src` attribute, only the `data-src`. This PR adds a `key` based on the passed `src` so `React` is re-renders the whole tag when the src changes. 
**Compare:**
https://kiwi--celsia.myvtex.com/
https://celsia.myvtex.com/
**Flow:**
1) Focus on search bar
2) Type `samsung`
3) Change the sku variation and see if the image changes
n/a
> Remount lazy loaded images when src changes

- CHANGELOG.md
- react/components/canUseDOM.ts
- react/core/main.tsx
- react/typings/runtime.ts
canUseDOM was not being exported as a type
Link this and then link an app after running `vtex setup --typings`
You can see in this workspace that I have the vtex.format-currency app linked:
https://breno--storecomponents.myvtex.com/
I rendered null if canUseDOM is true
n/a
n/a
> Fix exported type of canUseDOM and culture

- CHANGELOG.md
- react/package.json
- react/utils/events.ts
- react/yarn.lock
Fixes a bug where updating styles would no emit events thus not hot-reloading styles.
[Issue on Store Discussion](https://github.com/vtex-apps/store-discussion/issues/435).
- Go to [Workspace](https://styles--beightoneagency.myvtex.com/pao?_q=pao&map=ft)
- Link an app or theme that has styles.json or css overrides.
- Make changes on any styles files.
- Observe that hot-reloading now works.
N/A
N/A
> Fix: Styles update event not being emitted

- CHANGELOG.md
- react/hooks/viewDetection.tsx
As the title says
If the user scrolls the page before JS being initialized, the user interaction detection is not triggered until the user scrolls again. This PR checks if the page scroll is >0 and triggers the event right away if that's the case
Workspace:
https://mercado.carrefour.com.br/?workspace=lbebberfixfold5&v=04
Basically just open the page and interact with it to see if it breaks.
Then, scroll down to about the middle of the page, and refresh the page, and *keep the mouse still*. The page content should appear without user interaction.
After/Before demonstration (note the red bar on the header appearing--that's when the page has been hydrated in this case)
Related with https://github.com/vtex/render-server/pull/695
> Fix fold issue - user scrolling the page before JS being initialized

- CHANGELOG.md
- manifest.json
- react/utils/client/links/uriSwitchLink.ts
On our Splunk logs, we've identified several `orderForm`-like queries that were coming as `GET /_v/public/graphql`. This is erratic as these queries should always be private. Coming like that, there's a chance that some of these requests get a cache hit on some layer.
We've tried forcing the private scope on the queries itself but later realized that such work would need to be replicated on other queries/apps. Since this is a critical issue for us, we've agreed that the downside of sometimes (the unusual scenario of query-map changing on an user's session) using our private routes to "public" queries is worth.
Test [here](https://lucis--storecomponents.myvtex.com)
> Switching fallback to scope: private on GraphQL queries

- CHANGELOG.md
- react/components/RenderProvider.tsx
- react/core/main.tsx
- react/typings/runtime.ts
- react/utils/host.ts
- react/utils/routes.ts
- visit: https://ioqa.myvtexprod.com/?workspace=felipe2
- or: https://ioqa.vtexcommercestable.com.br/?workspace=felipe2
- Agora vai: https://github.com/vtex-apps/render-runtime/pull/580
> Make render8 pages work for stores running on portal 2, Return of the Jedi

- CHANGELOG.md
- react/externals.json
Updates render-session to 1.9.2 ([this PR](https://github.com/vtex-apps/render-session/pull/31)).
> Update render-session to 1.9.2

- CHANGELOG.md
- react/components/RenderProvider.tsx
- react/core/main.tsx
- react/package.json
- react/yarn.lock
The aim of this PR is to make legacy extension components reflect `locale` changes. To do that, we are making of `locale`   a `key` to `IntlProvider`, so all of its childs will be properly re-rendered.
- Use this [workspace](https://jeff--muji.vtexcommercebeta.com.br/checkout/cart/add/?sku=20362&qty=1&seller=1&sc=7)
- Check if `shipping-preview` and `omnishipping` are properly translated to Finnish.
N/A
This depends on and will only be effective after https://github.com/vtex/vcs.checkout-ui/pull/966 is merged.
> CHK-480: Fix locale update

- CHANGELOG.md
- react/components/ExtensionPoint/index.tsx
- react/components/LayoutContainer.tsx
- react/typings/runtime.ts
- react/utils/pages.ts
Blocks that are under fold block sometimes not render in the blocks list of the site editor. It disables that performance feature in this scenario.
https://vitorflg--muji.myvtex.com/admin/cms/site-editor
Create a different component/logic flow for the site editor and the end-client render, but it would need a big refactoring.
X
> Disable folding on the site editor

- CHANGELOG.md
- react/components/ExtensionPoint/ComponentLoader.tsx
- react/components/ExtensionPoint/index.tsx
- react/typings/global.d.ts
- react/typings/runtime.ts
Change the site editor identifier. A flag added to the admin-pages now permits us to better recognize if a page is being requested in the admin or not.
https://vitorflg--muji.myvtex.com/admin/cms/site-editor
X
X
> Disable hydrate-on-view on the site editor

- CHANGELOG.md
- react/utils/slots.tsx
1. A component with `composition: "children"`
```json
{
"my-custom-context": {
"component": "MyContextProvider",
"composition": "children"
}
}
```
2. A component that uses slots:
```json
{
"productWrapper#custompdpcontext": {
"props": {
"CustomContext": "my-custom-context"
}
}
}
```
3. In the `productWrapper` React component we have:
```tsx
function ProductWrapper({ children, CustomContext }) {
const CustomContextElement = CustomContext || Fragment
return (
<CustomContextElement>
{children}
</CustomContextElement>
)
}
```
The block `my-custom-context` doesn't have any blocks in it's block definition (which will be used as children):
The current code in master considers the empty blocks array as a value, overriding the prop `children` used in the React code.
This PR checks if the blocks …
> Use props children in slots if their slot children prop is empty

- CHANGELOG.md
- docs/README.md
- react/components/RenderContext.tsx
- react/components/useRuntime.ts
- react/components/withRuntimeContext.tsx
- react/core/main.tsx
As the title says...
Link `vtex.render-runtime` and run `vtex setup --typings`. After the change 👇
> Add 'pages' and 'route' to useRuntime and fix RenderContext and withRuntimeContext exported types definition

- CHANGELOG.md
- react/components/RenderProvider.tsx
The context for this change is in the [#prod-muji-eu](https://vtex.slack.com/archives/C01619D8146/p1614199934018700) channel.
As the title says, it adds a new param to the localesChanged event handler for a custom callback, considering that could be other options besides a page reload.
https://www.loom.com/share/0ea28c9573754baeb8d7d96e3ded5156
https://vitorflg--muji.myvtex.com/admin/cms/site-editor
X
It's a PR that support another one -> https://github.com/vtex-apps/admin-pages/pull/374
> Add a custom callback param to the localesChanged event

- CHANGELOG.md
- react/components/Prefetch/PrefetchContext.tsx
The prefetch queue listener is not triggered when the document has already been loaded. So, in this case, instead of adding a listener, we could just start the queue to make prefetch work in all scenarios.
https://vitorflg--storecomponents.myvtex.com/
Prefetch should work in all scenarios.
X
X
> Extend prefetch scenarios

- CHANGELOG.md
- manifest.json
- react/utils/pages.test.ts
- react/utils/pages.ts
It fixes a bug in basically every production store when searching three terms. The requests were being blocked by the WAF that we have on Azion, because they contained double encoded strings. You can simulate the behavior, for example, going to polishop.com.br and trying to search for "fritadeira air fryer". Once you go to the Network tab, you'll see that you receive a `400`, as the image below:
You can check in the following image that, instead of having `fritadeira%20air%20fryer` in the path, you will find `fritadeira%2520air%2520fryer`. This is due to the fact that the package that we use to join the path using the terms object already encodes the string. However, the strings were already reaching the RouteParser's method encoded.
In order for us to fix the problem without removing the …
> Decoding parameters to avoid double encoding while using route-parser

- react/components/RenderProvider.tsx
The `locale` is not being passed to the `localesChanged` event callback, it's a need for a custom logic on admin-pages.
[WIP]
X
[WIP]
> Pass locale as arg to the localesChanged event callback

- CHANGELOG.md
- react/core/main.tsx
Adds flag that signals that hydration is done. Intended for using with lazy pixel loading
Refer to https://github.com/vtex/render-server/pull/723/ for more details
> Hydration flag

- CHANGELOG.md
- docs/README.md
- react/components/RenderProvider.tsx
- react/utils/pages.ts
This PR adds a filter to Link params. This filter prevents all params that start with `__` from being considered during path transformations. This was added to safely allow the usage of params that are sent between pages but shouldn't be added to the query params due to user experience compromises.
[Workspace](http://icarorender--storecomponents.myvtex.com)
[Workspace 2](http://icarogtm--storecomponents.myvtex.com)
> Adding internal params identifiable via __ prefix

- CHANGELOG.md
- react/components/Link.tsx
This PR adds the `rel` prop to the `Link` component, allowing it to declare the relationship between the link and the current document
By updating the render-runtime app, the `rel` prop should be available to use whenever the `Link` component is declared
It was a suggestion made by the reviewers/contributors of another PR, I'll post the link in the section below
https://github.com/vtex-apps/store-link/pull/29
> added rel prop for better SEO

- CHANGELOG.md
- react/components/Link.tsx
This PR fixes a previous implementation where the `rel` prop is added, but it isn't passed down to the child component, resulting in a prop that is accepted and doesn't give errors, but it doesn't do anything.
Wherever a store-link is added to the theme, adding the "rel" prop actually makes use of said prop.
https://github.com/vtex-apps/render-runtime/pull/618
> Rel prop passed down in the return statement

- manifest.json
- react/utils/flags.ts
Disables the logic that does automatic prefetching. This is a very expensive feature that is not really useful in practice, as the prefetch takes longer than the time for the user to click the links.
Using [this workspace](https://mairaprefetch--storecomponents.myvtex.com/shirt?_q=shirt&map=ft) follow these steps:
1. Open the Network inspector tab of your browser.
2. Mouse over the page's links (products, categories, brands, etc).
3. Verify that no new requests with the `__pickRuntime` query string are made (**tip**: _filter by `__pickRuntime` in the network tab_).
Doing these exact same steps in the [master workspace](https://storecomponents.myvtex.com/shirt?_q=shirt&map=ft) will show a bunch of new requests with the `__pickRuntime` query string as you mouse over page links.
> Disable automatic link prefetching

- CHANGELOG.md
- react/components/RenderProvider.tsx
This PR prevents the page scroll being reset to `top: 0, left: 0` during page navigation if the navigation was initiated by the browser's back button. This allows the user to return to the previous scroll position when going back to the PLP after viewing a PDP, for example. 
Linked here: https://arthur--renwil.myvtex.com/mirrors?__bindingAddress=www.renwil.com/en
Scroll partway down the page, click on a product to go to the PDP, then click the Back button. You should return to the same scroll position that you were previously viewing.
> Fix: return to previous scroll position during back button navigation

- react/error.tsx
- react/utils/isAdmin.ts
Add additional information to the sentry admin instrumentation, like: `account`, `workspace`, `device`, whether is in `production`  or not, `locale`, and `path`. 
In [this workspace](https://lucasan--storecomponents.myvtex.com/admin/catalog) you can open the `console.log` and check the data sent whenever an error on production occurs.
> chore: add admin information to the sentry capture exception event

- CHANGELOG.md
- manifest.json
- react/error.tsx
This PR adds a runtime information retrieval fallback while logging errors to Sentry. It adds redundancy to make sure that we have the information we want available to debug our services.
Test environments (development):
- https://sentryiteration2--teamadmin.myvtex.com/admin 
- https://sentryiteration2break--teamadmin.myvtex.com/admin (Render server throws error _with runtime information available_)
- https://sentryiteration2breaknoruntime--teamadmin.myvtex.com/admin (Render server throws error _with **no** runtime information available **relies on fallback**_)
For richer details, reach out on Slack :hugs:
> feat: runtime retrieval fallback to log errors - ADMT-532

- CHANGELOG.md
- manifest.json
- react/components/ErrorBoundary.tsx
- react/error.tsx
- react/o11y/ctx.ts
- react/o11y/extraArgs.ts
- react/o11y/instrument.ts
- react/o11y/types.ts
This PR is a follow up from #660 that attempts to ensure that VTEX context is present in every log on Sentry through its auto-instrumentation middleware `beforeSend`. 
It moves all logic that retrieves and inserts VTEX context into the payload to Sentry to the aforementioned hook.
It also creates a mechanism to allow sending events to Sentry on development environments programatically.
[Reach out on Slack for more information on testing these changes](https://vtex.slack.com/archives/C07EHD840N6/p1723661822897809).
Related to:
- https://github.com/vtex/render-server/pull/800
> feat: log extra args through auto-instrumentation - ADMT-535

- .gitignore
- CHANGELOG.md
- manifest.json
- react/error.tsx
- react/o11y/extractExtra.test.ts
- react/o11y/extractExtra.ts
We need to index certain types of errors that are not yet indexed. To do this, we need to transform error objects into a "taggable" structure (such as key:value pairs). This PR adds a method to recursively extract keys from objects and adapt them to the our convention and signature expected on Sentry.
For more details, let's talk on Slack :hugs: 
Tests:
Depends on https://github.com/vtex/render-server/pull/801 to take effect.
> feat: add method to index certain errors on Sentry - ADMT-541

- CHANGELOG.md
- react/components/Link.tsx
Revert to browser native navigation based on the feature flag `useDefaultBrowserNavigation`, this is causing a behavior in FastStore accounts where a user cannot navigate to different pages without fully reload
https://github.com/vtex-apps/store/pull/597
> [SFOC-95] Feat: add featureFlag to force native browser navigation
