vtex-apps/render-runtime

- react/utils/pages.js
We need to make `/segment/*path` match `/segment`. We were already trying to do that in the code below:
https://github.com/vtex-apps/render-runtime/blob/1b69e74284faa29ec7bc816edda08cebbaf0a7bf/react/utils/pages.js#L41-L51
But that has a bug. If we have a route `/segment/*path/_meta`, the code above incorrectly consider `/segment/lalaland` a match.
`route-parser` already has optional segments support and we should use that to be less error-prone.
This PR transforms the path templates ending with `/*param` into ones ending with `(/*param)`, making the last splat capture optional. It does nothing in any other case.
> Fix routing by making the last splat capture optional

- react/package.json
- react/utils/client.js
- react/yarn.lock
Solves the infinite retry loop on network error by upgrading to new apollo-link-persisted-queries. Also, disables  persisted queries on any error.
> Disables persisted queries on any error and stop retrying after one single retry

- public/externals.json
- react/ExtensionPoint.js
- react/components/BuildStatus.js
- react/components/ExtensionPointComponent.js
- react/components/RenderProvider.js
- react/utils/events.js
- react/yarn.lock
Thanks @augustocb @ntmedina @gabrielgalc !!!
> Add build feedback during HMR

- react/components/Link.js
- react/components/RenderProvider.js
- react/utils/pages.js
It also enables a new type of navigation. You just need to say the page and the parameters.
> Add navigate method

- manifest.json
- public/externals.json
Depends on: 
https://github.com/vtex/render-server/pull/117
> Add request capture script to externals (only on client)

- manifest.json
- react/components/RenderProvider.tsx
- react/index.tsx
- react/package.json
- react/typings/global.d.ts
- react/typings/node.d.ts
- react/utils/appMessages.graphql
- react/utils/cacheControl.ts
- react/utils/client/generateHash.ts
- react/utils/client/index.ts
- react/utils/client/links/cachingLink.ts
- react/utils/client/links/uriSwitchLink.ts
- react/utils/client/links/versionSplitterLink.ts
- react/utils/events.ts
- react/utils/host.ts
- react/utils/messages.graphql
- react/utils/messages.ts
- react/utils/runtime.graphql
- react/utils/runtime.ts
- react/yarn.lock
Sends graphql query to endpoint /_v/v{version}/${scope}/graphql with defaults of version = 1 and scope = public
> Changes graphql endpoint according to context directive

- manifest.json
- react/utils/treePath.ts
Sorts extension points to enable ordering in extension container
> Sorts extension containers to allow page ordering

- manifest.json
- react/utils/client/index.ts
- react/utils/client/links/omitVariableTypenameLink.ts
This is a problem reported in https://github.com/apollographql/apollo-client/issues/1564 
with best solution found in https://github.com/apollographql/apollo-client/issues/1564#issuecomment-357492659
> Ommits variable __typename in apollo link

- manifest.json
- react/package.json
- react/utils/client/index.ts
- react/utils/client/links/ioFetchLink.ts
- react/utils/client/links/omitVariableTypenameLink.ts
- react/yarn.lock
Adds graphql file upload support using apollo-upload-client.
> GraphQL File Upload

- CHANGELOG.md
- manifest.json
- react/utils/client/index.ts
Adds default behavior to persisted query link
> Adding default behavior on disable persisted queries

- CHANGELOG.md
- manifest.json
- react/components/MaybeAuth.tsx
- react/components/NestedExtensionPoints.tsx
- Update MabeAuth to work Top-Down
- Fix Children with missing props in the `MaybeAuth` component
[/account/summary](https://claudivan2--storecomponents.myvtex.com/account/summary)
> Update MaybeAuth to work top-down

- CHANGELOG.md
- manifest.json
- react/components/RenderProvider.tsx
- react/utils/routes.ts
This reverts commit dfc701baf84da7df36874c054a444aecf5f233a8.
> Revert "Adding cache-and-network policy for faster page loading"

- CHANGELOG.md
- manifest.json
- react/components/MaybeAuth.tsx
- Add treatment of session authentication to `MaybeAuth`.
https://claudivan--storecomponents.myvtex.com/account/orders
> Add treatment of session authentication to `MaybeAuth`

- CHANGELOG.md
- manifest.json
- react/utils/session.tsx
Fix bug ifinite calls
[workspace](https://felipe--storecomponents.myvtex.com/admin/cms/storefront)
> Infinity calls when using fetchWithRetry in initializeSession and patchSession.

- react/package.json
- react/utils/client/generateHash.ts
- react/utils/client/index.ts
- react/utils/client/links/uriSwitchLink.ts
- react/utils/client/links/versionSplitterLink.ts
- react/yarn.lock
Solves lint issues with apollo
> Fix graphql related lint issues

- CHANGELOG.md
- manifest.json
- react/components/RenderProvider.tsx
- react/core/main.tsx
- react/utils/assets.ts
Also improve the performance of adding assets by not going through the entire list for every asset
> Preload assets instead of evaluating on prefetch

- CHANGELOG.md
- manifest.json
- react/utils/assets.ts
Well... Preload styles are breaking master too...
> Add the crossOrigin attribute to preload scripts/styles too

- CHANGELOG.md
- manifest.json
- public/externals.json
As the title says.
Fixes error messages, as per https://github.com/vtex-apps/render-session/pull/1
> Upgrade vtex-render-session version

- public/externals.json
Remove Fabriga as default font family.
> Update to vtex-tachyons@3

- CHANGELOG.md
- react/components/BuildStatus.tsx
- react/components/Loading.tsx
Remove the `store/__loading` extension. 
Depends on: https://github.com/vtex-apps/store/pull/144
> Loading svg is loaded by Icon Pack

- CHANGELOG.md
- manifest.json
- react/components/RenderProvider.tsx
- react/package.json
- react/queries/appMessages.graphql
- react/queries/messages.graphql
- react/queries/navigationPage.graphql
- react/queries/routePreviews.graphql
- react/typings/global.d.ts
- react/utils/messages.ts
- react/utils/routes.ts
Reverts vtex-apps/render-runtime#214
> Restore IOMessage

- CHANGELOG.md
- manifest.json
- react/components/LayoutContainer.tsx
- react/typings/global.d.ts
- react/utils/treePath.tsx
This will enable us to add/remove/reorder blocks consistently.
> Use blocks on LayoutContainer

- CHANGELOG.md
- manifest.json
- react/components/ExtensionPoint.tsx
- react/typings/global.d.ts
Extension now has a content field that is merged with block component props.
> Add content to extension

- CHANGELOG.md
- manifest.json
- react/components/Loading.tsx
Removes default spinner from component loader
> Remove default spinner

- CHANGELOG.md
- manifest.json
- react/components/RenderProvider.tsx
Uses window.reload on locale switcher
> Language window reload

- CHANGELOG.md
- manifest.json
- react/components/ChildBlock.tsx
- react/core/main.tsx
This feature makes it possible to check the existence of a child block.
It is useful for developing a component, such as Header, which will create a compat mode that will check for the existence of the new block if it's not present will render the legacy block.
> Add hook and component Child Block

- CHANGELOG.md
- manifest.json
- react/components/RenderProvider.tsx
- react/typings/global.d.ts
- react/utils/routes.ts
To disable user blocks query string `disableUserLand`, is passed through navigation
> Disable user land

- CHANGELOG.md
- manifest.json
- react/components/ExtensionPoint.tsx
- react/typings/global.d.ts
As the title says.
Works in tandem with https://github.com/vtex/builder-hub/pull/456 and https://github.com/vtex/pages-graphql/pull/153
> Update from layoutMode to composition

- CHANGELOG.md
- manifest.json
- react/components/Link.tsx
Test it [here](https://iraja--storecomponents.myvtex.com)
I've applied `prettier`, but in a separate commit.
> Add query to href in the Link component

- CHANGELOG.md
- manifest.json
- react/components/Link.tsx
Test it [here](https://grajau--boticario.myvtex.com/).
I've applied prettier, but in a separate commit.
> Add query to Link's href

- README.md
Check the README [here](https://github.com/vtex-apps/render-runtime/tree/feature/docs)
> Adding documentation to README.md

- CHANGELOG.md
- manifest.json
- react/components/RenderProvider.tsx
Exports render major to child context
> Render major to child context

- CHANGELOG.md
- manifest.json
- react/core/main.tsx
- react/utils/registerComponent.tsx
- react/utils/withHMR.tsx
Uses new function to register component instead of withHRM
> Register component

- CHANGELOG.md
- manifest.json
- react/components/ScopeMessagesHandler.tsx
- react/utils/registerComponent.tsx
Scope messages using `withScopeMessagesHandler` and `registerComponent` for HMR wrapping.
> Scope messages

- CHANGELOG.md
- manifest.json
- public/externals.json
https://github.com/vtex-apps/render-session/commit/40532b1e2683aba76c1a236a57e31118755ae818
> Fix render-session API call query string creation

- CHANGELOG.md
- manifest.json
- react/components/RenderProvider.tsx
- react/utils/assets.ts
https://github.com/GoogleChromeLabs/preload-webpack-plugin/issues/8
> Use prefetch instead of preload

- CHANGELOG.md
- manifest.json
- react/components/RenderProvider.tsx
This change affected the preview of the pages. We should address this more carefully having the benefits of loading faster but also showing the preview elements.
Test workspace:
https://breno--ecowaterqa.myvtexdev.com/
> Revert previous release

- CHANGELOG.md
- manifest.json
- react/components/RenderProvider.tsx
merges cache hints to avoid losing data
> Fix bypass-graphql

- react/utils/pages.ts
- Considers the case where there is a hash after the query on navigate function
> Considers hashes after the query string

- react/utils/pages.ts
> Don't add hash if it is undefined

- react/core/main.tsx
- react/typings/global.d.ts
> Set Lazy Cookie

- CHANGELOG.md
- public/externals.json
upgrades render-session after this [pr](https://github.com/vtex-apps/render-session/pull/6)
> Upgrade render session

- CHANGELOG.md
- manifest.json
- react/components/Session.tsx
- react/core/main.tsx
- react/error.tsx
Previously it was not possible to have a link with `<a rel="noopener nofollow">`
> Fix `rel` to make it possible to add more than one

- CHANGELOG.md
- react/components/RenderProvider.tsx
- react/core/main.tsx
- react/queries/navigationPage.graphql
- react/typings/global.d.ts
- react/utils/blocks.ts
- react/utils/routes.ts
This one unpacks `pages-graphql` reduced size extensions.
> Feature unpack extensions

- public/externals.json
https://unpkg.com/vtex-render-session@1.4.0/dist/index.js
> Update render-session to use global rootPath

- CHANGELOG.md
- react/components/MaybeContext.tsx
`pageContextProps` should be spread instead of being passed as is.
> Fix page context

- react/components/MaybeContext.test.tsx
> Add test case for MaybeContext pageContextProps bug.

- CHANGELOG.md
- react/utils/client/index.ts
Fixes the `undefined@undefined` in apollo cache
> Remove undefined@undefined from apollo cache locator

- CHANGELOG.md
- react/components/RenderProvider.tsx
- react/typings/global.d.ts
- react/utils/assets.ts
- react/utils/components.ts
Check for assets in bundled urls to fetch only necessary ones.
> Bundle assets

- react/utils/pages.ts
Reverts vtex-apps/render-runtime#391
> Revert "[WIP] Navigate lowercase"

- CHANGELOG.md
- react/components/ExtensionPoint.tsx
https://guilherme--storecomponents.myvtex.com/
> Add loading animation to client blocks

- CHANGELOG.md
- react/components/RenderProvider.tsx
Previews navigation page if it is known.
> Improves navigation preview

- CHANGELOG.md
- react/components/RenderProvider.tsx
- react/typings/global.d.ts
- react/utils/blocks.ts
- Add `contentIds` to opened extensions to facilitate extension's applied content usage.
> Add contentIds to extensions

- CHANGELOG.md
- react/utils/withHMR.tsx
https://searchnew--storecomponents.myvtex.com/top?_q=top&map=ft
ensure everything works fine
> do not let withHMR pass treePath prop to its wrapped component

- CHANGELOG.md
- react/utils/reactApollo.tsx
https://ssr--exitocol.myvtex.com/horno-microondas-09pc-negro-740604/p
> stop refetch breaking change in query component

- CHANGELOG.md
- react/components/RenderProvider.tsx
fix: https://github.com/vtex-apps/store-discussion/issues/120
https://fidelis--storecomponents.myvtex.com
> fix route class renaming when navigating with render

- manifest.json
- react/components/RenderProvider.tsx
- react/externals.json
- react/utils/client/index.ts
- react/utils/client/links/ensureSessionLink.ts
- react/utils/client/links/uriSwitchLink.ts
Makes the session query in the beginning of the rendering. 
Also, this PR awaits for queries only when fetching private/segment queries
> Session first

- CHANGELOG.md
- react/components/RenderProvider.tsx
- react/utils/assets.ts
- react/utils/events.ts
Listen to `styleOverrides` event and make CSS link refresh.
> CSS Overrides hot reload

- CHANGELOG.md
- react/components/Link.tsx
- react/components/RenderProvider.tsx
- react/package.json
- react/typings/global.d.ts
- react/utils/pages.ts
- react/yarn.lock
- Remove store url normalisation logic
- Add navigation route normalisation hook that will be used by store: [https://github.com/vtex-apps/store/tree/feature/navigation-path-normalization]
> Add navigation route modifier hooks for store URL normalisation

- CHANGELOG.md
- react/components/RenderProvider.tsx
- react/typings/global.d.ts
- react/utils/client/links/uriSwitchLink.ts
- react/utils/location.ts
- react/utils/pages.ts
Add `binding` to runtime, expose `__bindingAddress` in URL and add `__bindingId` query string to GraphQL requests.
> Bindings support

- CHANGELOG.md
- react/components/LoadingContext.tsx
- react/components/RenderProvider.tsx
- react/typings/global.d.ts
- react/utils/assets.ts
- react/utils/components.ts
Some improvements in selecting assets to fetch.
Fetch all components as you navigate
Makes us able to render the product page as soon as the product is loaded
https://wfbeta--boticario.myvtex.com/
https://wfbeta--alssports.myvtex.com/
https://wfbeta--exitocol.myvtex.com/
https://wfbeta--tbb.myvtex.com/
https://wfbeta--paguemenos.myvtex.com/
https://wfbeta--samsungar.myvtex.com/
> fetch assets as you navigate

- CHANGELOG.md
- react/components/RenderProvider.tsx
- react/utils/components.ts
- react/utils/routes.ts
- We were fetching way too many components, now we only fetch the necessary, those that come from the extensions.
https://wfbeta--alssports.myvtex.com/
https://wfbeta--boticario.myvtex.com/
https://wfbeta--tbb.myvtex.com/
https://wfbeta--exitocol.myvtex.com/
> only fetch components in extensions

- CHANGELOG.md
- react/components/RenderProvider.tsx
> Accumulate messages

- CHANGELOG.md
- react/components/RenderProvider.tsx
This should fix some binding switching issues.
> Always set vtex_binding_address cookie

- CHANGELOG.md
- react/utils/vteximg.ts
https://fidelis--alssports.myvtex.com/
> replace vteximg.com.br to vtexassets.com in img elements

- CHANGELOG.md
- react/externals.json
- react/package.json
- react/yarn.lock
This should remove about 54kB from the page's size
> Removes sentry from externals.json

- CHANGELOG.md
- react/components/useRuntime.ts
- react/core/main.tsx
This way, it's types can be generated and shared between VTEX IO apps
> Add useRuntime.ts file at react/components/ folder

- CHANGELOG.md
- react/utils/client/links/uriSwitchLink.ts
> Use post for queries in b2b scenarios

- CHANGELOG.md
- react/core/main.tsx
- react/typings/global.d.ts
Depends on https://github.com/vtex/render-server/pull/602
> Avoid phantom cached query strings

- CHANGELOG.md
- react/utils/assets.ts
With the new multiple links for tachyons stylesheets, we now have to get all links with the style_link class and iterate over them to update each
> adapt tachyons hotreload for multipl links

- CHANGELOG.md
- react/components/Prefetch/PrefetchContext.tsx
- react/utils/flags.ts
- react/utils/routes.ts
We can make master safe again and keep the prefetch code in there, but nothing will happen because the feature flag will be off
> turn prefetch off

- CHANGELOG.md
- manifest.json
- react/index.tsx
- react/typings/global.d.ts
- react/utils/assets.ts
> Change strategy to include uncritical CSS assets

- CHANGELOG.md
- manifest.json
> bump version

- CHANGELOG.md
- react/index.tsx
- react/start/amp.ts
- react/start/intl.ts
- react/start/patchLibs.ts
- react/start/register.ts
- react/start/runtime.ts
- react/start/uncritical.ts
- react/typings/global.d.ts
Prevents from adding __RUNTIME__ et al as an inline script, instead adding them inline as a <template>.
See: https://github.com/vtex/render-server/pull/660
> Lazy init runtime JSON

- CHANGELOG.md
- react/components/RenderProvider.tsx
- react/core/main.tsx
- react/start/runtime.ts
- react/utils/apolloCache.ts
- react/utils/client/index.ts
- react/utils/client/links/runtimeContextLink.ts
- react/utils/events.ts
- react/utils/promise.ts
Does `hydrateApolloCache` separately from the `hydrate` from React, which reduces total blocking time
Also splits the `hydrateApolloCache` into multiple smaller ones, reducing the blocking time further.
Before (dev workspace, heavy search page):
After (dev workspace, heavy search page):
Before (prod workspace, heavy search page):
After (prod workspace, heavy search page):
Before (one single hydrateApolloCache task):
After (split hydrateApolloCache task, highlighting the longest one):
https://www.carrefour.com.br/Celulares-Smartphones-e-Smartwatches/Smartphones?ak-testab=vtex&workspace=lbebberapollo1
Production workspace: https://www.carrefour.com.br/Celulares-Smartphones-e-Smartwatches/Smartphones?ak-testab=vtex&workspace=apollohydrate
Development workspace: …
> Split hydrateApolloCache

- CHANGELOG.md
- react/index.tsx
- react/typings/global.d.ts
Wait the execution of async scripts to start rendering.
Working here: https://storetheme.vtex.com/?workspace=brunohp
https://github.com/vtex/render-server/pull/667
https://github.com/vtex/asset-server/pull/56
> Async Scripts

- CHANGELOG.md
- react/core/main.tsx
- react/externals.json
- react/start/runtime.ts
- react/typings/global.d.ts
- react/typings/react-dom/experimental.d.ts
- react/utils/apolloCache.ts
- react/utils/dom.tsx
- react/utils/promise.ts
- react/utils/withDevice.tsx
Enable react concurrent mode with a feature flag. This PR was based on this draft: https://github.com/vtex-apps/render-runtime/pull/563
It is linked here https://brunoh--storecomponents.myvtex.com/
https://github.com/vtex/render-server/pull/670
> React Concurrent Mode

- CHANGELOG.md
- react/components/RenderProvider.tsx
- react/utils/pages.ts
Add the loading bar on top of the document when redirecting to checkout.
In the workspace, try to add to cart or use the `go to checkout` button of the minicart. The redirect should occur with a presence of a loading bar on top of the document.
https://vitorflg--storecomponents.myvtex.com/
X
X
> Loading when redirecting

- CHANGELOG.md
- react/components/RenderProvider.tsx
- react/utils/pages.ts
Rollback to the last stable version.
N/A
N/A
N/A
> Rollback v8.123.0

- CHANGELOG.md
- react/components/ExtensionPoint/index.tsx
Fixes this:
n/a
n/a
https://github.com/vtex-apps/menu/pull/116
> Add generic prop typing to `ExtensionPoint`

- CHANGELOG.md
- react/components/ChildBlock.tsx
- react/components/useChildBlock.tsx
- react/core/main.tsx
Only default exports types are accessible.
https://autocompletets--storecomponents.myvtex.com/
> Fix types of useChildBlock and ChilBlock

- CHANGELOG.md
- react/components/RenderProvider.tsx
- react/core/main.tsx
- react/typings/runtime.ts
- react/utils/host.ts
- react/utils/routes.ts
- ditto.
- https://feirissima.vtexcommercestable.com.br/_secure/account?workspace=felipe#/subscriptions
- visit the Subscriptions on my-account page
> Make render8 pages work for stores running on portal

- CHANGELOG.md
- react/utils/components.ts
It fixes the components conflict algorithm (see #547) that was detecting conflict between components with different majors.
https://brunoh--storecomponents.myvtex.com/
Open the home page and navigate to any of the products on the shelf, it won't scroll to the top and do a server-side navigation, as happens in master (https://storecomponents.myvtex.com/)
> Fix components conflict check

- CHANGELOG.md
- react/components/Link.tsx
- react/components/Prefetch/PrefetchLink.tsx
> Fix Link and PrefetchLink types

- CHANGELOG.md
- manifest.json
- public/config.json
- react/components/ExtensionPointComponent.tsx
- react/package.json
- react/start.ts
- react/yarn.lock
Remove Sentry (error tracking tool) from Render Runtime 7.x.
> Remove Sentry from Render Runtime 7

- CHANGELOG.md
- react/externals.json
- Update react version to 17.0.2
- Workspace: https://react17--recorrenciaqa.myvtex.com/.
- Adding it as an "alternative".
- Are there any other modules that I should be concerned about?
- Could this impact users in an unexpected way?
> Update react to version 17.0.2

- CHANGELOG.md
- react/components/ExtensionPoint/index.tsx
and this with the class added: 
- Considered other names for such class;
- Tried with cssHandles but failed because of a dependency cycle detected:
> added tachyons class

- CHANGELOG.md
- manifest.json
- react/ExtensionContainer.tsx
- react/LayoutContainer.tsx
- react/LegacyExtensionContainer.tsx
- react/error.tsx
- react/externals.json
- react/index.tsx
- react/o11y/instrument.ts
- react/package.json
- react/utils/isAdmin.ts
- react/yarn.lock
This PR instruments the Admin environment (Admin and all Render Admin Apps) with Sentry.
For more details, get in touch with me on Slack.
> feat: sentry - ADMT-491

- CHANGELOG.md
- react/components/Link.tsx
> Fix missing optional chaining in useDefaultBrowserNavigation prop
